spring:
  application:
    name: banana-config
  profiles:
    active: native
#  boot:
#    admin:
#      client:
#        url: http://127.0.0.1:10011
  cloud:
    config:
      server:
        native:
          search-locations: /home/config/
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:2020/eureka/
  instance:
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
server:
  port: 10010
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"